<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64;x86</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Interfaces\UseCases\Stock\Cliente\ProcesarClienteStockHanaUseCase.cs" />
    <Compile Remove="Interfaces\UseCases\Stock\Dealer\ProcesarClienteStockHanaUseCase.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Mapster" Version="7.4.0" />
    <PackageReference Include="Mapster.DependencyInjection" Version="1.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.1" />
    <PackageReference Include="Polly" Version="8.6.5" />
    <PackageReference Include="System.Data.Odbc" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="SAPBusinessOneSDK">
      <HintPath>..\Shared\Dependencies\SAPBusinessOneSDK.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
