using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Domain.SAP
{
 
        // Root myDeserializedClass = JsonConvert.Deserializestring<Root>(myJsonResponse);
        public class AddressExtension
        {
            public string ShipToStreet { get; set; }
            public string ShipToStreetNo { get; set; }
            public string ShipToBlock { get; set; }
            public string ShipToBuilding { get; set; }
            public string ShipToCity { get; set; }
            public string ShipToZipCode { get; set; }
            public string ShipToCounty { get; set; }
            public string ShipToState { get; set; }
            public string ShipToCountry { get; set; }
            public string ShipToAddressType { get; set; }
            public string BillToStreet { get; set; }
            public string BillToStreetNo { get; set; }
            public string BillToBlock { get; set; }
            public string BillToBuilding { get; set; }
            public string BillToCity { get; set; }
            public string BillToZipCode { get; set; }
            public string BillToCounty { get; set; }
            public string BillToState { get; set; }
            public string BillToCountry { get; set; }
            public string BillToAddressType { get; set; }
            public string ShipToGlobalLocationNumber { get; set; }
            public string BillToGlobalLocationNumber { get; set; }
            public string ShipToAddress2 { get; set; }
            public string ShipToAddress3 { get; set; }
            public string BillToAddress2 { get; set; }
            public string BillToAddress3 { get; set; }
            public string PlaceOfSupply { get; set; }
            public string PurchasePlaceOfSupply { get; set; }
            public int DocEntry { get; set; }
            public string GoodsIssuePlaceBP { get; set; }
            public string GoodsIssuePlaceCNPJ { get; set; }
            public string GoodsIssuePlaceCPF { get; set; }
            public string GoodsIssuePlaceStreet { get; set; }
            public string GoodsIssuePlaceStreetNo { get; set; }
            public string GoodsIssuePlaceBuilding { get; set; }
            public string GoodsIssuePlaceZip { get; set; }
            public string GoodsIssuePlaceBlock { get; set; }
            public string GoodsIssuePlaceCity { get; set; }
            public string GoodsIssuePlaceCounty { get; set; }
            public string GoodsIssuePlaceState { get; set; }
            public string GoodsIssuePlaceCountry { get; set; }
            public string GoodsIssuePlacePhone { get; set; }
            public string GoodsIssuePlaceEMail { get; set; }
            public string GoodsIssuePlaceDepartureDate { get; set; }
            public string DeliveryPlaceBP { get; set; }
            public string DeliveryPlaceCNPJ { get; set; }
            public string DeliveryPlaceCPF { get; set; }
            public string DeliveryPlaceStreet { get; set; }
            public string DeliveryPlaceStreetNo { get; set; }
            public string DeliveryPlaceBuilding { get; set; }
            public string DeliveryPlaceZip { get; set; }
            public string DeliveryPlaceBlock { get; set; }
            public string DeliveryPlaceCity { get; set; }
            public string DeliveryPlaceCounty { get; set; }
            public string DeliveryPlaceState { get; set; }
            public string DeliveryPlaceCountry { get; set; }
            public string DeliveryPlacePhone { get; set; }
            public string DeliveryPlaceEMail { get; set; }
            public string DeliveryPlaceDepartureDate { get; set; }
            public string U_num_autorizacionS { get; set; }
            public string U_num_autorizacionB { get; set; }
            public string U_EstablecimientoS { get; set; }
            public string U_EstablecimientoB { get; set; }
            public string U_Punto_EmisionS { get; set; }
            public string U_Punto_EmisionB { get; set; }
            public string U_Rango_iniS { get; set; }
            public string U_Rango_iniB { get; set; }
            public string U_Rango_finalS { get; set; }
            public string U_Rango_finalB { get; set; }
            public string U_Fecha_Vig_iniS { get; set; }
            public string U_Fecha_Vig_iniB { get; set; }
            public string U_Fecha_Vig_finS { get; set; }
            public string U_Fecha_Vig_finB { get; set; }
        }

        public class DocumentLine
        {
            public int LineNum { get; set; }
            public string ItemCode { get; set; }
            public string ItemDescription { get; set; }
            public double Quantity { get; set; }
            public string ShipDate { get; set; }
            public double Price { get; set; }
            public double PriceAfterVAT { get; set; }
            public string Currency { get; set; }
            public double Rate { get; set; }
            public double DiscountPercent { get; set; }
            public string VendorNum { get; set; }
            public string SerialNum { get; set; }
            public string WarehouseCode { get; set; }
            public int SalesPersonCode { get; set; }
            public double CommisionPercent { get; set; }
            public string TreeType { get; set; }
            public string AccountCode { get; set; }
            public string UseBaseUnits { get; set; }
            public string SupplierCatNum { get; set; }
            public string CostingCode { get; set; }
            public string ProjectCode { get; set; }
            public string BarCode { get; set; }
            public string VatGroup { get; set; }
            public double Height1 { get; set; }
            public string Hight1Unit { get; set; }
            public double Height2 { get; set; }
            public string Height2Unit { get; set; }
            public double Lengh1 { get; set; }
            public string Lengh1Unit { get; set; }
            public double Lengh2 { get; set; }
            public string Lengh2Unit { get; set; }
            public double Weight1 { get; set; }
            public string Weight1Unit { get; set; }
            public double Weight2 { get; set; }
            public string Weight2Unit { get; set; }
            public double Factor1 { get; set; }
            public double Factor2 { get; set; }
            public double Factor3 { get; set; }
            public double Factor4 { get; set; }
            public int BaseType { get; set; }
            public int BaseEntry { get; set; }
            public int BaseLine { get; set; }
            public double Volume { get; set; }
            public int VolumeUnit { get; set; }
            public double Width1 { get; set; }
            public string Width1Unit { get; set; }
            public double Width2 { get; set; }
            public string Width2Unit { get; set; }
            public string Address { get; set; }
            public string TaxCode { get; set; }
            public string TaxType { get; set; }
            public string TaxLiable { get; set; }
            public string PickStatus { get; set; }
            public double PickQuantity { get; set; }
            public string PickListIdNumber { get; set; }
            public string OriginalItem { get; set; }
            public string BackOrder { get; set; }
            public string FreeText { get; set; }
            public int ShippingMethod { get; set; }
            public string POTargetNum { get; set; }
            public string POTargetEntry { get; set; }
            public string POTargetRowNum { get; set; }
            public string CorrectionInvoiceItem { get; set; }
            public double CorrInvAmountToStock { get; set; }
            public double CorrInvAmountToDiffAcct { get; set; }
            public double AppliedTax { get; set; }
            public double AppliedTaxFC { get; set; }
            public double AppliedTaxSC { get; set; }
            public string WTLiable { get; set; }
            public string DeferredTax { get; set; }
            public double EqualizationTaxPercent { get; set; }
            public double TotalEqualizationTax { get; set; }
            public double TotalEqualizationTaxFC { get; set; }
            public double TotalEqualizationTaxSC { get; set; }
            public double NetTaxAmount { get; set; }
            public double NetTaxAmountFC { get; set; }
            public double NetTaxAmountSC { get; set; }
            public string MeasureUnit { get; set; }
            public double UnitsOfMeasurment { get; set; }
            public double LineTotal { get; set; }
            public double TaxPercentagePerRow { get; set; }
            public double TaxTotal { get; set; }
            public string ConsumerSalesForecast { get; set; }
            public double ExciseAmount { get; set; }
            public double TaxPerUnit { get; set; }
            public double TotalInclTax { get; set; }
            public string CountryOrg { get; set; }
            public string SWW { get; set; }
            public string TransactionType { get; set; }
            public string DistributeExpense { get; set; }
            public double RowTotalFC { get; set; }
            public double RowTotalSC { get; set; }
            public double LastBuyInmPrice { get; set; }
            public double LastBuyDistributeSumFc { get; set; }
            public double LastBuyDistributeSumSc { get; set; }
            public double LastBuyDistributeSum { get; set; }
            public double StockDistributesumForeign { get; set; }
            public double StockDistributesumSystem { get; set; }
            public double StockDistributesum { get; set; }
            public double StockInmPrice { get; set; }
            public string PickStatusEx { get; set; }
            public double TaxBeforeDPM { get; set; }
            public double TaxBeforeDPMFC { get; set; }
            public double TaxBeforeDPMSC { get; set; }
            public string CFOPCode { get; set; }
            public string CSTCode { get; set; }
            public string Usage { get; set; }
            public string TaxOnly { get; set; }
            public int VisualOrder { get; set; }
            public double BaseOpenQuantity { get; set; }
            public double UnitPrice { get; set; }
            public string LineStatus { get; set; }
            public double PackageQuantity { get; set; }
            public string Text { get; set; }
            public string LineType { get; set; }
            public string COGSCostingCode { get; set; }
            public string COGSAccountCode { get; set; }
            public string ChangeAssemlyBoMWarehouse { get; set; }
            public double GrossBuyPrice { get; set; }
            public int GrossBase { get; set; }
            public double GrossProfitTotalBasePrice { get; set; }
            public string CostingCode2 { get; set; }
            public string CostingCode3 { get; set; }
            public string CostingCode4 { get; set; }
            public string CostingCode5 { get; set; }
            public string ItemDetails { get; set; }
            public string LocationCode { get; set; }
            public DateTime ActualDeliveryDate { get; set; }
            public double RemainingOpenQuantity { get; set; }
            public double OpenAmount { get; set; }
            public double OpenAmountFC { get; set; }
            public double OpenAmountSC { get; set; }
            public string ExLineNo { get; set; }
            public string RequiredDate { get; set; }
            public double RequiredQuantity { get; set; }
            public string COGSCostingCode2 { get; set; }
            public string COGSCostingCode3 { get; set; }
            public string COGSCostingCode4 { get; set; }
            public string COGSCostingCode5 { get; set; }
            public string CSTforIPI { get; set; }
            public string CSTforPIS { get; set; }
            public string CSTforCOFINS { get; set; }
            public string CreditOriginCode { get; set; }
            public string WithoutInventoryMovement { get; set; }
            public string AgreementNo { get; set; }
            public string AgreementRowNumber { get; set; }
            public string ActualBaseEntry { get; set; }
            public string ActualBaseLine { get; set; }
            public int DocEntry { get; set; }
            public double Surpluses { get; set; }
            public double DefectAndBreakup { get; set; }
            public double Shortages { get; set; }
            public string ConsiderQuantity { get; set; }
            public string PartialRetirement { get; set; }
            public double RetirementQuantity { get; set; }
            public double RetirementAPC { get; set; }
            public string ThirdParty { get; set; }
            public string PoNum { get; set; }
            public string PoItmNum { get; set; }
            public string ExpenseType { get; set; }
            public string ReceiptNumber { get; set; }
            public string ExpenseOperationType { get; set; }
            public string FederalTaxID { get; set; }
            public double GrossProfit { get; set; }
            public double GrossProfitFC { get; set; }
            public double GrossProfitSC { get; set; }
            public string PriceSource { get; set; }
            public string StgSeqNum { get; set; }
            public string StgEntry { get; set; }
            public string StgDesc { get; set; }
            public int UoMEntry { get; set; }
            public string UoMCode { get; set; }
            public double InventoryQuantity { get; set; }
            public double RemainingOpenInventoryQuantity { get; set; }
            public string ParentLineNum { get; set; }
            public int Incoterms { get; set; }
            public int TransportMode { get; set; }
            public string NatureOfTransaction { get; set; }
            public string DestinationCountryForImport { get; set; }
            public string DestinationRegionForImport { get; set; }
            public string OriginCountryForExport { get; set; }
            public string OriginRegionForExport { get; set; }
            public string ItemType { get; set; }
            public string ChangeInventoryQuantityIndependently { get; set; }
            public string FreeOfChargeBP { get; set; }
            public string SACEntry { get; set; }
            public string HSNEntry { get; set; }
            public double GrossPrice { get; set; }
            public double GrossTotal { get; set; }
            public double GrossTotalFC { get; set; }
            public double GrossTotalSC { get; set; }
            public int NCMCode { get; set; }
            public string NVECode { get; set; }
            public string IndEscala { get; set; }
            public double CtrSealQty { get; set; }
            public string CNJPMan { get; set; }
            public int CESTCode { get; set; }
            public string UFFiscalBenefitCode { get; set; }
            public string ReverseCharge { get; set; }
            public string ShipToCode { get; set; }
            public string ShipToDescription { get; set; }
            public int OwnerCode { get; set; }
            public double ExternalCalcTaxRate { get; set; }
            public double ExternalCalcTaxAmount { get; set; }
            public double ExternalCalcTaxAmountFC { get; set; }
            public double ExternalCalcTaxAmountSC { get; set; }
            public int StandardItemIdentification { get; set; }
            public int CommodityClassification { get; set; }
            public double WeightOfRecycledPlastic { get; set; }
            public string PlasticPackageExemptionReason { get; set; }
            public string LegalText { get; set; }
            public string Cig { get; set; }
            public string Cup { get; set; }
            public string OperatingProfit { get; set; }
            public string OperatingProfitFC { get; set; }
            public string OperatingProfitSC { get; set; }
            public string NetIncome { get; set; }
            public string NetIncomeFC { get; set; }
            public string NetIncomeSC { get; set; }
            public string UnencumberedReason { get; set; }
            public string CUSplit { get; set; }
            public string ListNum { get; set; }
            public string RecognizedTaxCode { get; set; }
            public string U_EXX_FE_ValICEVta { get; set; }
            public string U_EXX_FE_PorICEVta { get; set; }
            public double U_ECC_STOCK_R { get; set; }
            public List<LineTaxJurisdiction> LineTaxJurisdictions { get; set; }
            public List<string> ExportProcesses { get; set; }
            public List<string> DocumentLineAdditionalExpenses { get; set; }
            public List<string> WithholdingTaxLines { get; set; }
            public List<string> SerialNumbers { get; set; }
            public List<string> BatchNumbers { get; set; }
            public List<string> CCDNumbers { get; set; }
            public List<string> DocumentLinesBinAllocations { get; set; }
        }

        public class EWayBillDetails
        {
        }

        public class LineTaxJurisdiction
        {
            public string JurisdictionCode { get; set; }
            public int JurisdictionType { get; set; }
            public double TaxAmount { get; set; }
            public double TaxAmountSC { get; set; }
            public double TaxAmountFC { get; set; }
            public double TaxRate { get; set; }
            public int DocEntry { get; set; }
            public int LineNumber { get; set; }
            public int RowSequence { get; set; }
            public double ExternalCalcTaxRate { get; set; }
            public double ExternalCalcTaxAmount { get; set; }
            public double ExternalCalcTaxAmountFC { get; set; }
            public double ExternalCalcTaxAmountSC { get; set; }
            public double BaseSum { get; set; }
            public string TaxInPrice { get; set; }
            public double NonDeductiblePercent { get; set; }
            public string TaxOnReserveInvoice { get; set; }
            public string Exempt { get; set; }
            public string Unencumbered { get; set; }
        }

        public class DeliveryNotesSAP
        {
            public string odataetag { get; set; }
            public int DocEntry { get; set; }
            public int DocNum { get; set; }
            public string DocType { get; set; }
            public string HandWritten { get; set; }
            public string Printed { get; set; }
            public DateTime DocDate { get; set; }
            public DateTime DocDueDate { get; set; }
            public string CardCode { get; set; }
            public string CardName { get; set; }
            public string Address { get; set; }
            public string NumAtCard { get; set; }
            public double DocTotal { get; set; }
            public string AttachmentEntry { get; set; }
            public string DocCurrency { get; set; }
            public double DocRate { get; set; }
            public string Reference1 { get; set; }
            public string Reference2 { get; set; }
            public string Comments { get; set; }
            public string JournalMemo { get; set; }
            public int PaymentGroupCode { get; set; }
            public string DocTime { get; set; }
            public int SalesPersonCode { get; set; }
            public int TransportationCode { get; set; }
            public string Confirmed { get; set; }
            public string ImportFileNum { get; set; }
            public string SummeryType { get; set; }
            public int ContactPersonCode { get; set; }
            public string ShowSCN { get; set; }
            public int Series { get; set; }
            public DateTime TaxDate { get; set; }
            public string PartialSupply { get; set; }
            public string DocstringCode { get; set; }
            public string ShipToCode { get; set; }
            public string Indicator { get; set; }
            public string FederalTaxID { get; set; }
            public double DiscountPercent { get; set; }
            public string PaymentReference { get; set; }
            public DateTime CreationDate { get; set; }
            public DateTime UpdateDate { get; set; }
            public int FinancialPeriod { get; set; }
            public int UserSign { get; set; }
            public int TransNum { get; set; }
            public double VatSum { get; set; }
            public double VatSumSys { get; set; }
            public double VatSumFc { get; set; }
            public string NetProcedure { get; set; }
            public double DocTotalFc { get; set; }
            public double DocTotalSys { get; set; }
            public string Form1099 { get; set; }
            public string Box1099 { get; set; }
            public string RevisionPo { get; set; }
            public string RequriedDate { get; set; }
            public string CancelDate { get; set; }
            public string BlockDunning { get; set; }
            public string Submitted { get; set; }
            public int Segment { get; set; }
            public string PickStatus { get; set; }
            public string Pick { get; set; }
            public string PaymentMethod { get; set; }
            public string PaymentBlock { get; set; }
            public string PaymentBlockEntry { get; set; }
            public string CentralBankIndicator { get; set; }
            public string MaximumCashDiscount { get; set; }
            public string Reserve { get; set; }
            public string Project { get; set; }
            public string ExemptionValidityDateFrom { get; set; }
            public string ExemptionValidityDateTo { get; set; }
            public string WareHouseUpdateType { get; set; }
            public string Rounding { get; set; }
            public string ExternalCorrectedDocNum { get; set; }
            public string InternalCorrectedDocNum { get; set; }
            public string NextCorrectingDocument { get; set; }
            public string DeferredTax { get; set; }
            public string TaxExemptionLetterNum { get; set; }
            public double WTApplied { get; set; }
            public double WTAppliedFC { get; set; }
            public string BillOfExchangeReserved { get; set; }
            public string AgentCode { get; set; }
            public double WTAppliedSC { get; set; }
            public double TotalEqualizationTax { get; set; }
            public double TotalEqualizationTaxFC { get; set; }
            public double TotalEqualizationTaxSC { get; set; }
            public int NumberOfInstallments { get; set; }
            public string ApplyTaxOnFirstInstallment { get; set; }
            public string TaxOnInstallments { get; set; }
            public double WTNonSubjectAmount { get; set; }
            public double WTNonSubjectAmountSC { get; set; }
            public double WTNonSubjectAmountFC { get; set; }
            public double WTExemptedAmount { get; set; }
            public double WTExemptedAmountSC { get; set; }
            public double WTExemptedAmountFC { get; set; }
            public double BaseAmount { get; set; }
            public double BaseAmountSC { get; set; }
            public double BaseAmountFC { get; set; }
            public double WTAmount { get; set; }
            public double WTAmountSC { get; set; }
            public double WTAmountFC { get; set; }
            public string VatDate { get; set; }
            public int DocumentsOwner { get; set; }
            public string FolioPrefixString { get; set; }
            public string FolioNumber { get; set; }
            public string DocumentSubType { get; set; }
            public string BPChannelCode { get; set; }
            public string BPChannelContact { get; set; }
            public string Address2 { get; set; }
            public string DocumentStatus { get; set; }
            public string PeriodIndicator { get; set; }
            public string PayToCode { get; set; }
            public string ManualNumber { get; set; }
            public string UseShpdGoodsAct { get; set; }
            public string IsPayToBank { get; set; }
            public string PayToBankCountry { get; set; }
            public string PayToBankCode { get; set; }
            public string PayToBankAccountNo { get; set; }
            public string PayToBankBranch { get; set; }
            public string BPL_IDAssignedToInvoice { get; set; }
            public double DownPayment { get; set; }
            public string ReserveInvoice { get; set; }
            public int LanguageCode { get; set; }
            public string TrackingNumber { get; set; }
            public string PickRemark { get; set; }
            public string ClosingDate { get; set; }
            public string SequenceCode { get; set; }
            public string SequenceSerial { get; set; }
            public string SeriesString { get; set; }
            public string SubSeriesString { get; set; }
            public string SequenceModel { get; set; }
            public string UseCorrectionVATGroup { get; set; }
            public double TotalDiscount { get; set; }
            public double DownPaymentAmount { get; set; }
            public double DownPaymentPercentage { get; set; }
            public string DownPaymentType { get; set; }
            public double DownPaymentAmountSC { get; set; }
            public double DownPaymentAmountFC { get; set; }
            public double VatPercent { get; set; }
            public string ServiceGrossProfitPercent { get; set; }
            public string OpeningRemarks { get; set; }
            public string ClosingRemarks { get; set; }
            public double RoundingDiffAmount { get; set; }
            public double RoundingDiffAmountFC { get; set; }
            public double RoundingDiffAmountSC { get; set; }
            public string Cancelled { get; set; }
            public string SignatureInputMessage { get; set; }
            public string SignatureDigest { get; set; }
            public string CertificationNumber { get; set; }
            public string PrivateKeyVersion { get; set; }
            public string ControlAccount { get; set; }
            public string InsuranceOperation347 { get; set; }
            public string ArchiveNonremovableSalesQuotation { get; set; }
            public string GTSChecker { get; set; }
            public string GTSPayee { get; set; }
            public int ExtraMonth { get; set; }
            public int ExtraDays { get; set; }
            public int CashDiscountDateOffset { get; set; }
            public string StartFrom { get; set; }
            public string NTSApproved { get; set; }
            public string ETaxWebSite { get; set; }
            public string ETaxNumber { get; set; }
            public string NTSApprovedNumber { get; set; }
            public string EDocGenerationType { get; set; }
            public string EDocSeries { get; set; }
            public string EDocNum { get; set; }
            public string EDocExportFormat { get; set; }
            public string EDocStatus { get; set; }
            public string EDocErrorCode { get; set; }
            public string EDocErrorMessage { get; set; }
            public string DownPaymentStatus { get; set; }
            public string GroupSeries { get; set; }
            public string GroupNumber { get; set; }
            public string GroupHandWritten { get; set; }
            public string ReopenOriginalDocument { get; set; }
            public string ReopenManuallyClosedOrCanceledDocument { get; set; }
            public string CreateOnlineQuotation { get; set; }
            public string POSEquipmentNumber { get; set; }
            public string POSManufacturerSerialNumber { get; set; }
            public string POSCashierNumber { get; set; }
            public string ApplyCurrentVATRatesForDownPaymentsToDraw { get; set; }
            public string ClosingOption { get; set; }
            public string SpecifiedClosingDate { get; set; }
            public string OpenForLandedCosts { get; set; }
            public string AuthorizationStatus { get; set; }
            public double TotalDiscountFC { get; set; }
            public double TotalDiscountSC { get; set; }
            public string RelevantToGTS { get; set; }
            public string BPLName { get; set; }
            public string VATRegNum { get; set; }
            public string AnnualInvoiceDeclarationReference { get; set; }
            public string Supplier { get; set; }
            public string Releaser { get; set; }
            public string Receiver { get; set; }
            public string BlanketAgreementNumber { get; set; }
            public string IsAlteration { get; set; }
            public string CancelStatus { get; set; }
            public string AssetValueDate { get; set; }
            public string DocumentDelivery { get; set; }
            public string AuthorizationCode { get; set; }
            public string StartDeliveryDate { get; set; }
            public string StartDeliveryTime { get; set; }
            public string EndDeliveryDate { get; set; }
            public string EndDeliveryTime { get; set; }
            public string VehiclePlate { get; set; }
            public string ATDocumentType { get; set; }
            public string ElecCommStatus { get; set; }
            public string ElecCommMessage { get; set; }
            public string ReuseDocumentNum { get; set; }
            public string ReuseNotaFiscalNum { get; set; }
            public string PrintSEPADirect { get; set; }
            public string FiscalDocNum { get; set; }
            public string POSDailySummaryNo { get; set; }
            public string POSReceiptNo { get; set; }
            public string PointOfIssueCode { get; set; }
            public string Letter { get; set; }
            public string FolioNumberFrom { get; set; }
            public string FolioNumberTo { get; set; }
            public string InterimType { get; set; }
            public int RelatedType { get; set; }
            public string RelatedEntry { get; set; }
            public string SAPPassport { get; set; }
            public string DocumentTaxID { get; set; }
            public string DateOfReportingControlStatementVAT { get; set; }
            public string ReportingSectionControlStatementVAT { get; set; }
            public string ExcludeFromTaxReportControlStatementVAT { get; set; }
            public string POS_CashRegister { get; set; }
            public string UpdateTime { get; set; }
            public string CreateQRCodeFrom { get; set; }
            public string PriceMode { get; set; }
            public string ShipFrom { get; set; }
            public string CommissionTrade { get; set; }
            public string CommissionTradeReturn { get; set; }
            public string UseBillToAddrToDetermineTax { get; set; }
            public string Cig { get; set; }
            public string Cup { get; set; }
            public string FatherCard { get; set; }
            public string FatherType { get; set; }
            public string ShipState { get; set; }
            public string ShipPlace { get; set; }
            public string CustOffice { get; set; }
            public string FCI { get; set; }
            public string AddLegIn { get; set; }
            public string LegTextF { get; set; }
            public string DANFELgTxt { get; set; }
            public string IndFinal { get; set; }
            public int DataVersion { get; set; }
            public string LastPageFolioNumber { get; set; }
            public string InventoryStatus { get; set; }
            public string PlasticPackagingTaxRelevant { get; set; }
            public string NotRelevantForMonthlyInvoice { get; set; }
            public string AllocationNumberIL { get; set; }
            public string EndAt { get; set; }
            public string U_SER_EST { get; set; }
            public string U_SER_PE { get; set; }
            public string U_NUM_AUTOR { get; set; }
            public string U_COD_ST { get; set; }
            public string U_SER_EST_FR { get; set; }
            public string U_SER_PEFR { get; set; }
            public string U_NUM_AUT_FR { get; set; }
            public string U_NUM_FAC_REL { get; set; }
            public string U_COMP_RET { get; set; }
            public string U_SERIE_RET { get; set; }
            public string U_NUM_AUT_RET { get; set; }
            public string U_FEC_INI_TRAS { get; set; }
            public string U_FEC_FIN_TRAS { get; set; }
            public string U_fecha_emi_doc_rel { get; set; }
            public string U_NUM_DECLAR_ADU { get; set; }
            public string U_MOT_TRASLADO { get; set; }
            public string U_PUNTO_PART { get; set; }
            public string U_NUM_GUIA { get; set; }
            public string U_CORRELATIVO { get; set; }
            public string U_VERIFICADOR { get; set; }
            public string U_TRANSPORTE { get; set; }
            public string U_TRANSPORTISTA { get; set; }
            public string U_FECHA_EMBARQUE { get; set; }
            public string U_Exx_IP_Pago { get; set; }
            public string U_Exx_IP_Pais { get; set; }
            public string U_Exx_IP_DobleTrib { get; set; }
            public string U_Exx_IP_SujetRet_NL { get; set; }
            public string U_Exx_FechaRet { get; set; }
            public string U_Exx_Rembolso { get; set; }
            public string U_Exx_FPagxDoc { get; set; }
            public string U_TIP_DOC_APLIC { get; set; }
            public string U_tipo_export { get; set; }
            public string U_tipo_comprob { get; set; }
            public string U_DOC_DECLARABLE { get; set; }
            public string U_DISTRITO_ADU { get; set; }
            public string U_REFRENDO_ANIO { get; set; }
            public string U_REFRENDO_REG { get; set; }
            public double U_VALOR_FOB { get; set; }
            public string U_NUM_DOC_TRANSP { get; set; }
            public string U_NUM_FUE { get; set; }
            public string U_MOT_NC { get; set; }
            public string U_MOT_ND { get; set; }
            public string U_EXX_FE_TIPCOM { get; set; }
            public string U_EXX_FE_TIPAMB { get; set; }
            public string U_EXX_FE_CODNUM { get; set; }
            public string U_EXX_FE_TIPEMI { get; set; }
            public string U_EXX_FE_DIFVER { get; set; }
            public string U_EXX_FE_FECAUT { get; set; }
            public string U_Exx_Din_Cons { get; set; }
            public string U_Exx_FE_Paisdestin { get; set; }
            public string U_Exx_pagoRegFis { get; set; }
            public string U_Exx_fechaPagoDiv { get; set; }
            public double U_Exx_imRentaSoc { get; set; }
            public string U_Exx_anioUtDiv { get; set; }
            public string U_Exx_numCajBan { get; set; }
            public double U_Exx_precCajBan { get; set; }
            public string U_Exx_doc_compensac { get; set; }
            public string U_EXX_COMPENSADO { get; set; }
            public string U_EXX_FPAGO_COMPRAS { get; set; }
            public string U_EXX_FPAGO_VENTAS { get; set; }
            public double U_EXX_VAL_COMP { get; set; }
            public string U_EXX_FACT_NEG { get; set; }
            public string U_Exx_DenoFiscal { get; set; }
            public string U_Exx_ingFueGra_IR { get; set; }
            public string U_Exx_Paraiso_Fis { get; set; }
            public string U_Exx_TipIngExt { get; set; }
            public string U_Exx_TipRegFis { get; set; }
            public double U_Exx_ValoImpExt { get; set; }
            public string U_CLAVE_ACCESO { get; set; }
            public string U_ESTADO_AUTORIZACIO { get; set; }
            public string U_NUM_AUTO_FAC { get; set; }
            public string U_FECHA_AUT_FACT { get; set; }
            public string U_OBSERVACION_FACT { get; set; }
            public string U_SSCREADAR { get; set; }
            public string U_SSIDDOCUMENTO { get; set; }
            public string U_EXX_CAIM { get; set; }
            public string U_BloqueoC { get; set; }
            public string U_K_Nom_Empl_Vta { get; set; }
            public string U_Com_Log { get; set; }
            public string U_FECHA_DESP { get; set; }
            public string U_Transportista_Log { get; set; }
            public string U_RECIBIDO_LOG { get; set; }
            public string U_LQ_CLAVE { get; set; }
            public string U_LQ_ESTADO { get; set; }
            public string U_LQ_NUM_AUTO { get; set; }
            public string U_LQ_FECHA_AUT { get; set; }
            public string U_LQ_OBSERVACION { get; set; }
            public string U_KC_AGENTE { get; set; }
            public string U_KC_NUM_TARJETAS { get; set; }
            public string U_SSGen4PV { get; set; }
            public string U_FV_OrdenC { get; set; }
            public string U_TipoPedido { get; set; }
            public string U_SS_SUSTRIB { get; set; }
            public string U_SS_Est { get; set; }
            public string U_SS_Pemi { get; set; }
            public string U_SS_NumAut { get; set; }
            public string U_SS_TipCom { get; set; }
            public string U_SS_EstFacRel { get; set; }
            public string U_SS_PunEmiFacRel { get; set; }
            public string U_SS_NumAutFacRel { get; set; }
            public string U_SS_NumFacRel { get; set; }
            public string U_SS_FecEmiDocRel { get; set; }
            public string U_SS_TipDocAplica { get; set; }
            public string U_SS_FormaPagos { get; set; }
            public string U_SS_MOTIVO_NC { get; set; }
            public string U_SS_NumGuia { get; set; }
            public string U_SS_FecIniTra { get; set; }
            public string U_SS_FecFinTra { get; set; }
            public string U_SS_HoraSal { get; set; }
            public string U_SS_HoraLLeg { get; set; }
            public string U_SS_PunPart { get; set; }
            public string U_SS_CodTra { get; set; }
            public string U_SS_Transportista { get; set; }
            public string U_SS_MotTraslado { get; set; }
            public string U_SS_DenoFiscal { get; set; }
            public string U_SS_ParFiscal { get; set; }
            public string U_SS_TipoExpor { get; set; }
            public string U_SS_ComercioExt { get; set; }
            public string U_SS_IncoTermFac { get; set; }
            public string U_SS_LugIncoTerm { get; set; }
            public string U_SS_PaisOrigen { get; set; }
            public string U_SS_PuertoEmb { get; set; }
            public string U_SS_PuertoDestino { get; set; }
            public string U_SS_PaisDestino { get; set; }
            public string U_SS_PaisAdqui { get; set; }
            public string U_SS_Incotermto { get; set; }
            public string U_SS_TipIngExt { get; set; }
            public string U_SS_IngFueGra { get; set; }
            public double U_SS_ValFob { get; set; }
            public string U_SS_RefrendoAnio { get; set; }
            public string U_SS_RefrendoReg { get; set; }
            public string U_SS_FechaEmb { get; set; }
            public string U_SS_DisAduanero { get; set; }
            public string U_SS_CodRegimen { get; set; }
            public string U_SS_Correlativo { get; set; }
            public string U_SS_Doc_Transporte { get; set; }
            public string U_SS_ValIrExt { get; set; }
            public string U_SS_SerieRet { get; set; }
            public string U_SS_SecRet { get; set; }
            public string U_SS_NumAutRet { get; set; }
            public string U_SS_FecRet { get; set; }
            public string U_SS_Reembolsos { get; set; }
            public string U_SS_InfPago { get; set; }
            public string U_SS_PROTESTO { get; set; }
            public string U_SS_SalTrans { get; set; }
            public string U_SS_BaseDestino { get; set; }
            public string U_SS_IdBodegaEnt { get; set; }
            public string U_SS_IdEntMer { get; set; }
            public string U_SS_EntTrans { get; set; }
            public string U_SS_BaseOrigen { get; set; }
            public string U_SS_IdBodegaSal { get; set; }
            public string U_SS_IdSalMer { get; set; }
            public string U_SS_IDRETCERO { get; set; }
            public List<string> Document_ApprovalRequests { get; set; }
            public List<DocumentLine> DocumentLines { get; set; }
            public EWayBillDetails EWayBillDetails { get; set; }
            public List<string> ElectronicProtocols { get; set; }
            public List<string> DocumentAdditionalExpenses { get; set; }
            public List<string> WithholdingTaxDataWTXCollection { get; set; }
            public List<string> WithholdingTaxDataCollection { get; set; }
            public List<string> DocumentPackages { get; set; }
            public List<string> DocumentSpecialLines { get; set; }
            public TaxExtension TaxExtension { get; set; }
            public AddressExtension AddressExtension { get; set; }
            public List<string> DocumentReferences { get; set; }
            public List<string> DocumentAdditionalIntrastatExpenses { get; set; }
        }

        public class TaxExtension
        {
            public string TaxId0 { get; set; }
            public string TaxId1 { get; set; }
            public string TaxId2 { get; set; }
            public string TaxId3 { get; set; }
            public string TaxId4 { get; set; }
            public string TaxId5 { get; set; }
            public string TaxId6 { get; set; }
            public string TaxId7 { get; set; }
            public string TaxId8 { get; set; }
            public string TaxId9 { get; set; }
            public string State { get; set; }
            public string County { get; set; }
            public string Incoterms { get; set; }
            public string Vehicle { get; set; }
            public string VehicleState { get; set; }
            public string NFRef { get; set; }
            public string Carrier { get; set; }
            public string PackQuantity { get; set; }
            public string PackDescription { get; set; }
            public string Brand { get; set; }
            public string ShipUnitNo { get; set; }
            public double NetWeight { get; set; }
            public double GrossWeight { get; set; }
            public string StreetS { get; set; }
            public string BlockS { get; set; }
            public string BuildingS { get; set; }
            public string CityS { get; set; }
            public string ZipCodeS { get; set; }
            public string CountyS { get; set; }
            public string StateS { get; set; }
            public string CountryS { get; set; }
            public string StreetB { get; set; }
            public string BlockB { get; set; }
            public string BuildingB { get; set; }
            public string CityB { get; set; }
            public string ZipCodeB { get; set; }
            public string CountyB { get; set; }
            public string StateB { get; set; }
            public string CountryB { get; set; }
            public string ImportOrExport { get; set; }
            public string MainUsage { get; set; }
            public string GlobalLocationNumberS { get; set; }
            public string GlobalLocationNumberB { get; set; }
            public string TaxId12 { get; set; }
            public string TaxId13 { get; set; }
            public string BillOfEntryNo { get; set; }
            public string BillOfEntryDate { get; set; }
            public string OriginalBillOfEntryNo { get; set; }
            public string OriginalBillOfEntryDate { get; set; }
            public string ImportOrExportType { get; set; }
            public string PortCode { get; set; }
            public int DocEntry { get; set; }
            public double BoEValue { get; set; }
            public string ClaimRefund { get; set; }
            public string DifferentialOfTaxRate { get; set; }
            public string IsIGSTAccount { get; set; }
            public string TaxId14 { get; set; }
        }


    }

